# Generated by Django 6.0.3 on 2026-04-02 16:35

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorsettings',
            name='secret',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
